// This file is auto-generated by @hey-api/openapi-ts


export enum EventMessageTypeModelEnum {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export enum ToDoItemStatusEnum {
    NONE = 'None',
    ACTIVE = 'Active',
    COMPLETED = 'Completed'
}

export enum ToDoListStatusEnum {
    OPEN = 'Open',
    COMPLETED = 'Completed',
    CLOSED = 'Closed'
}