// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class ToDoItemsService {
    /**
 * @returns number Success
 * @throws ApiError
 */
    public static count(): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Count']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/Count'
});
    }
    
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static delete(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Delete']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Delete']['delete']['res'][200]> {
        const { id } = data;
        return __request(OpenAPI, {
    method: 'DELETE',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/Delete',
    query: {
        id
    },
    responseHeader: 'Umb-Notifications'
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static get(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Get']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Get']['get']['res'][200]> {
        const { id } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/Get',
    query: {
        id
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getPaged(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/GetPaged']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/GetPaged']['get']['res'][200]> {
        const { page } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/GetPaged',
    query: {
        page
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getForList(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Items']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Items']['get']['res'][200]> {
        const { listKey } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/Items',
    query: {
        listKey
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static list(): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/List']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/List'
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static save(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Save']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/Item/Save']['post']['res'][200]> {
        const { requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/DoStuff/Api/v1/ToDo/Item/Save',
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}

export class ToDoListsService {
    /**
 * @returns number Success
 * @throws ApiError
 */
    public static count2(): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Count']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/Count'
});
    }
    
    /**
 * @returns string Success
 * @throws ApiError
 */
    public static delete2(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Delete']['delete']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Delete']['delete']['res'][200]> {
        const { id } = data;
        return __request(OpenAPI, {
    method: 'DELETE',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/Delete',
    query: {
        id
    },
    responseHeader: 'Umb-Notifications'
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static get2(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Get']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Get']['get']['res'][200]> {
        const { id } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/Get',
    query: {
        id
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getByNode(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/GetByNode']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/GetByNode']['get']['res'][200]> {
        const { nodeKey } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/GetByNode',
    query: {
        nodeKey
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static getPaged2(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/GetPaged']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/GetPaged']['get']['res'][200]> {
        const { page } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/GetPaged',
    query: {
        page
    }
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static list2(): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/List']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/List'
});
    }
    
    /**
 * @returns unknown Success
 * @throws ApiError
 */
    public static save2(data: $OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Save']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/DoStuff/Api/v1/ToDo/List/Save']['post']['res'][200]> {
        const { requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/DoStuff/Api/v1/ToDo/List/Save',
    body: requestBody,
    mediaType: 'application/json'
});
    }
    
}