// This file is auto-generated by @hey-api/openapi-ts


export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedModelToDoItemModel = {
    items: Array<(ToDoItem)>;
    total: number;
};

export type PagedModelToDoListModel = {
    items: Array<(ToDoList)>;
    total: number;
};

export type ToDoItem = {
    id: number;
    key: string;
    listKey: string;
    taskName: string;
    status: ToDoItemStatus;
};

export type ToDoItemStatus = 'None' | 'Active' | 'Completed';

export type ToDoList = {
    id: number;
    key: string;
    name: string;
    status: ToDoListStatus;
    nodeKey?: string | null;
    owner?: string | null;
};

export type ToDoListStatus = 'Open' | 'Completed' | 'Closed';

export type $OpenApiTs = {
    '/umbraco/DoStuff/Api/v1/ToDo/Item/Count': {
        get: {
            res: {
                /**
 * Success
 */
                200: number;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/Delete': {
        delete: {
            req: {
                id?: number;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/Get': {
        get: {
            req: {
                id?: number;
            };
            res: {
                /**
 * Success
 */
                200: ToDoItem;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/GetPaged': {
        get: {
            req: {
                page?: number;
            };
            res: {
                /**
 * Success
 */
                200: PagedModelToDoItemModel;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/Items': {
        get: {
            req: {
                listKey?: string;
            };
            res: {
                /**
 * Success
 */
                200: Array<(ToDoItem)>;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/List': {
        get: {
            res: {
                /**
 * Success
 */
                200: Array<(ToDoItem)>;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/Item/Save': {
        post: {
            req: {
                requestBody?: ToDoItem;
            };
            res: {
                /**
 * Success
 */
                200: ToDoItem;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/Count': {
        get: {
            res: {
                /**
 * Success
 */
                200: number;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/Delete': {
        delete: {
            req: {
                id?: number;
            };
            res: {
                /**
 * Success
 */
                200: string;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/Get': {
        get: {
            req: {
                id?: number;
            };
            res: {
                /**
 * Success
 */
                200: ToDoList;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/GetByNode': {
        get: {
            req: {
                nodeKey?: string;
            };
            res: {
                /**
 * Success
 */
                200: Array<(ToDoList)>;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/GetPaged': {
        get: {
            req: {
                page?: number;
            };
            res: {
                /**
 * Success
 */
                200: PagedModelToDoListModel;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/List': {
        get: {
            res: {
                /**
 * Success
 */
                200: Array<(ToDoList)>;
            };
        };
    };
    '/umbraco/DoStuff/Api/v1/ToDo/List/Save': {
        post: {
            req: {
                requestBody?: ToDoList;
            };
            res: {
                /**
 * Success
 */
                200: ToDoList;
            };
        };
    };
};