// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCurrentDateData, GetCurrentDateErrors, GetCurrentDateResponses, GetCurrentTimeData, GetCurrentTimeErrors, GetCurrentTimeResponses, GetTimeSettingsData, GetTimeSettingsErrors, GetTimeSettingsResponses, GetTimeZonesData, GetTimeZonesErrors, GetTimeZonesResponses, GetTimezoneTimeData, GetTimezoneTimeErrors, GetTimezoneTimeResponses, GetTimeZoneTimesData, GetTimeZoneTimesErrors, GetTimeZoneTimesResponses, PingData, PingErrors, PingResponses, SaveTimeSettingsData, SaveTimeSettingsErrors, SaveTimeSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class DoStuffClientService {
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/ping',
            ...options
        });
    }
}

export class TimeService {
    public static getCurrentDate<ThrowOnError extends boolean = false>(options?: Options<GetCurrentDateData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCurrentDateResponses, GetCurrentDateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetCurrentDate',
            ...options
        });
    }
    
    public static getCurrentTime<ThrowOnError extends boolean = false>(options?: Options<GetCurrentTimeData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCurrentTimeResponses, GetCurrentTimeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetCurrentTime',
            ...options
        });
    }
    
    public static getTimeZones<ThrowOnError extends boolean = false>(options?: Options<GetTimeZonesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTimeZonesResponses, GetTimeZonesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetTimeZones',
            ...options
        });
    }
    
    public static getTimezoneTime<ThrowOnError extends boolean = false>(options?: Options<GetTimezoneTimeData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTimezoneTimeResponses, GetTimezoneTimeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetTimezoneTime',
            ...options
        });
    }
    
    public static getTimeZoneTimes<ThrowOnError extends boolean = false>(options?: Options<GetTimeZoneTimesData, ThrowOnError>) {
        return (options?.client ?? client).post<GetTimeZoneTimesResponses, GetTimeZoneTimesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetTimeZoneTimes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class TimeSettingsService {
    public static getTimeSettings<ThrowOnError extends boolean = false>(options?: Options<GetTimeSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTimeSettingsResponses, GetTimeSettingsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/GetTimeSettings',
            ...options
        });
    }
    
    public static saveTimeSettings<ThrowOnError extends boolean = false>(options?: Options<SaveTimeSettingsData, ThrowOnError>) {
        return (options?.client ?? client).post<SaveTimeSettingsResponses, SaveTimeSettingsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dostuffclient/api/v1/SaveTimeSettings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
