// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44363' | (string & {});
};

export type TimeSettings = {
    id: number;
    key: string;
    userKey: string;
    refreshInterval: number;
    timeZones: Array<TimeZoneSetting>;
};

export type TimeZoneDisplayTime = {
    id: string;
    name?: string | null;
    value?: string | null;
};

export type TimeZoneInfo = {
    readonly id: string;
    readonly hasIanaId: boolean;
    readonly displayName: string;
    readonly standardName: string;
    readonly daylightName: string;
    readonly baseUtcOffset: string;
    readonly supportsDaylightSavingTime: boolean;
};

export type TimeZoneSetting = {
    id: string;
    name?: string | null;
};

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetCurrentDateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/GetCurrentDate';
};

export type GetCurrentDateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCurrentDateResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetCurrentDateResponse = GetCurrentDateResponses[keyof GetCurrentDateResponses];

export type GetCurrentTimeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/GetCurrentTime';
};

export type GetCurrentTimeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCurrentTimeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetCurrentTimeResponse = GetCurrentTimeResponses[keyof GetCurrentTimeResponses];

export type GetTimeZonesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/GetTimeZones';
};

export type GetTimeZonesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTimeZonesResponses = {
    /**
     * OK
     */
    200: Array<TimeZoneInfo>;
};

export type GetTimeZonesResponse = GetTimeZonesResponses[keyof GetTimeZonesResponses];

export type GetTimezoneTimeData = {
    body?: never;
    path?: never;
    query?: {
        timezone?: string;
    };
    url: '/umbraco/dostuffclient/api/v1/GetTimezoneTime';
};

export type GetTimezoneTimeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTimezoneTimeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetTimezoneTimeResponse = GetTimezoneTimeResponses[keyof GetTimezoneTimeResponses];

export type GetTimeZoneTimesData = {
    body?: Array<TimeZoneSetting>;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/GetTimeZoneTimes';
};

export type GetTimeZoneTimesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTimeZoneTimesResponses = {
    /**
     * OK
     */
    200: Array<TimeZoneDisplayTime>;
};

export type GetTimeZoneTimesResponse = GetTimeZoneTimesResponses[keyof GetTimeZoneTimesResponses];

export type GetTimeSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/GetTimeSettings';
};

export type GetTimeSettingsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTimeSettingsResponses = {
    /**
     * OK
     */
    200: TimeSettings;
};

export type GetTimeSettingsResponse = GetTimeSettingsResponses[keyof GetTimeSettingsResponses];

export type SaveTimeSettingsData = {
    body?: TimeSettings;
    path?: never;
    query?: never;
    url: '/umbraco/dostuffclient/api/v1/SaveTimeSettings';
};

export type SaveTimeSettingsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveTimeSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};
